name: gs
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  get: ^4.6.6
  gap: ^3.0.1
  flutter_animate: ^4.5.0
  convex_bottom_bar: ^3.0.0
  font_awesome_flutter: ^10.7.0

dev_dependencies:
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter
  build_runner:
  flutter_gen_runner:


flutter_gen:
  output: lib/Core/Gen

flutter:
  uses-material-design: true
  assets:
    - assets/gif/
    - assets/png/
    - assets/jpg/
    - assets/json/
    - assets/webp/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins/PoppinsLatin-Black.ttf
        - asset: assets/fonts/Poppins/PoppinsLatin-Bold.ttf
        - asset: assets/fonts/Poppins/PoppinsLatin-ExtraBold.ttf
        - asset: assets/fonts/Poppins/PoppinsLatin-ExtraLight.ttf
        - asset: assets/fonts/Poppins/PoppinsLatin-Light.ttf
        - asset: assets/fonts/Poppins/PoppinsLatin-Medium.ttf
        - asset: assets/fonts/Poppins/PoppinsLatin-Regular.ttf
        - asset: assets/fonts/Poppins/PoppinsLatin-SemiBold.ttf
        - asset: assets/fonts/Poppins/PoppinsLatin-Thin.ttf

    - family: Samurai
      fonts:
        - asset: assets/fonts/Samurai/SamuraiBlast.otf
